<?php

use CRM_Payarcjs_ExtensionUtil as E;

/**
 * Wallet buttons and card-testing limits. The settings page is created by the setting-admin mixin at
 * civicrm/admin/setting/payarcjs (Administer > System Settings).
 */
return [
  'payarcjs_apple_pay_enabled' => [
    'name' => 'payarcjs_apple_pay_enabled',
    'type' => 'Boolean',
    'html_type' => 'checkbox',
    'default' => FALSE,
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => E::ts('Offer Apple Pay on contribution pages'),
    'description' => E::ts('Shows a "Pay with Apple Pay" button above the card fields for one-time gifts, in browsers that support Apple Pay (Safari). The Apple Pay sheet opens in a small PayArc window, so this site needs no Apple merchant setup or domain file; the sheet names the payee "Payarc". Where Apple Pay is available, it is shown instead of Google Pay. Recurring gifts, back-office forms and card updates always use the card fields.'),
    'settings_pages' => ['payarcjs' => ['weight' => 1]],
  ],
  'payarcjs_google_pay_enabled' => [
    'name' => 'payarcjs_google_pay_enabled',
    'type' => 'Boolean',
    'html_type' => 'checkbox',
    'default' => FALSE,
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => E::ts('Offer Google Pay on contribution pages'),
    'description' => E::ts('Shows a "Pay with Google Pay" button above the card fields for one-time gifts, in browsers where Apple Pay is not offered. Google Pay opens in a small PayArc window. Recurring gifts, back-office forms and card updates always use the card fields.'),
    'settings_pages' => ['payarcjs' => ['weight' => 2]],
  ],
  'payarcjs_velocity_ip_limit' => [
    'name' => 'payarcjs_velocity_ip_limit',
    'type' => 'Integer',
    'html_type' => 'text',
    'html_attributes' => ['size' => 4],
    'default' => 5,
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => E::ts('Card-testing protection: declines per IP address'),
    'description' => E::ts('Bots test stolen cards by running many small payments through a contribution page, most of them declined. After this many declined or refused payments from one IP address within 60 minutes, that address is refused until an hour has passed since its first decline. Recurring installments are never counted or blocked, and staff with "edit contributions" are never blocked. 0 turns this off.'),
    'settings_pages' => ['payarcjs' => ['weight' => 10]],
  ],
  'payarcjs_client_ip_header' => [
    'name' => 'payarcjs_client_ip_header',
    'type' => 'String',
    'html_type' => 'text',
    'html_attributes' => ['size' => 24],
    'default' => '',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => E::ts('Card-testing protection: client IP header'),
    'description' => E::ts('Only for a site behind a proxy (such as Cloudflare) that does not pass on the visitor\'s address: without it, every payer shares the proxy\'s address and the per-IP limit refuses real donors. Enter the header the proxy sets, such as CF-Connecting-IP or X-Forwarded-For (the last address in the list is used). Leave blank otherwise: a visitor can send this header themselves, so on a site that is not behind that proxy it lets them change the address that is counted.'),
    'settings_pages' => ['payarcjs' => ['weight' => 15]],
  ],
  'payarcjs_velocity_site_limit' => [
    'name' => 'payarcjs_velocity_site_limit',
    'type' => 'Integer',
    'html_type' => 'text',
    'html_attributes' => ['size' => 4],
    'default' => 20,
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => E::ts('Card-testing protection: declines site-wide'),
    'description' => E::ts('After this many declined or refused payments from any addresses within 60 minutes, online card payments pause and the alert address is emailed. Attacks rotate IP addresses, so this is the limit that stops them. Raise it if a busy event could bring this many genuine declines in an hour. 0 turns this off.'),
    'settings_pages' => ['payarcjs' => ['weight' => 11]],
  ],
  'payarcjs_velocity_pause_minutes' => [
    'name' => 'payarcjs_velocity_pause_minutes',
    'type' => 'Integer',
    'html_type' => 'text',
    'html_attributes' => ['size' => 4],
    'default' => 60,
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => E::ts('Card-testing protection: pause length (minutes)'),
    'description' => E::ts('How long card payments stay paused. System Status shows a pause and can resume payments sooner.'),
    'settings_pages' => ['payarcjs' => ['weight' => 12]],
  ],
  'payarcjs_velocity_alert_email' => [
    'name' => 'payarcjs_velocity_alert_email',
    'type' => 'String',
    'html_type' => 'text',
    'html_attributes' => ['size' => 40],
    'default' => '',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => E::ts('Card-testing protection: alert email'),
    'description' => E::ts('Emailed once each time card payments pause. Blank uses the default "From" address of this organization.'),
    'settings_pages' => ['payarcjs' => ['weight' => 13]],
  ],
  'payarcjs_velocity_min_amount' => [
    'name' => 'payarcjs_velocity_min_amount',
    'type' => 'String',
    'html_type' => 'text',
    'html_attributes' => ['size' => 8],
    'default' => '0',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => E::ts('Card-testing protection: minimum card payment'),
    'description' => E::ts('Payments below this amount are refused (card testers use small amounts). 0 allows any amount. Card updates are not affected.'),
    'settings_pages' => ['payarcjs' => ['weight' => 14]],
  ],
];
